name: iliastsangaris
markdown: redcarpet
pygments: true
assets:
  dirname: assets
  baseurl: /assets/
  sources:
      - _assets/fonts
      - _assets/javascripts
      - _assets/stylesheets
      - _assets/images
  js_compressor: uglifier
  css_compressor: sass